name: jest
on:
  workflow_dispatch:
jobs:
  test: 
    runs-on: ubuntu-latest  # 実行環境はubuntu
    steps:
    - uses: actions/checkout@v1 # ソースをチェックアウト
    - name: Setup Node.js # node.jsをセットアップ
      uses: actions/setup-node@v1
      with:
        node-version: '14.17.x'
    - name: yarn install
      run: yarn install
    - name: Run jest test
      run: yarn test